

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."discord_channels" (
    "id" bigint NOT NULL,
    "channel_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."discord_channels" OWNER TO "postgres";


ALTER TABLE "public"."discord_channels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."discord_channels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."toban_workspaces" (
    "id" bigint NOT NULL,
    "chain_id" integer NOT NULL,
    "tree_id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."toban_workspaces" OWNER TO "postgres";


ALTER TABLE "public"."toban_workspaces" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."toban_workspaces_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."workspace_channel_relations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."workspace_channel_relations" OWNER TO "postgres";


ALTER TABLE "public"."workspace_channel_relations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."workspace_channel_relations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."toban_workspaces"
    ADD CONSTRAINT "chain_tree_unique" UNIQUE ("chain_id", "tree_id");



ALTER TABLE ONLY "public"."discord_channels"
    ADD CONSTRAINT "discord_channels_channel_id_key" UNIQUE ("channel_id");



ALTER TABLE ONLY "public"."discord_channels"
    ADD CONSTRAINT "discord_channels_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."toban_workspaces"
    ADD CONSTRAINT "toban_workspaces_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."workspace_channel_relations"
    ADD CONSTRAINT "workspace_channel_relations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."workspace_channel_relations"
    ADD CONSTRAINT "workspace_channel_relations_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."toban_workspaces"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."workspace_channel_relations"
    ADD CONSTRAINT "workspace_channel_relations_id_fkey1" FOREIGN KEY ("id") REFERENCES "public"."discord_channels"("id") ON DELETE CASCADE;



ALTER TABLE "public"."discord_channels" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."toban_workspaces" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."workspace_channel_relations" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."discord_channels" TO "anon";
GRANT ALL ON TABLE "public"."discord_channels" TO "authenticated";
GRANT ALL ON TABLE "public"."discord_channels" TO "service_role";



GRANT ALL ON SEQUENCE "public"."discord_channels_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."discord_channels_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."discord_channels_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."toban_workspaces" TO "anon";
GRANT ALL ON TABLE "public"."toban_workspaces" TO "authenticated";
GRANT ALL ON TABLE "public"."toban_workspaces" TO "service_role";



GRANT ALL ON SEQUENCE "public"."toban_workspaces_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."toban_workspaces_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."toban_workspaces_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."workspace_channel_relations" TO "anon";
GRANT ALL ON TABLE "public"."workspace_channel_relations" TO "authenticated";
GRANT ALL ON TABLE "public"."workspace_channel_relations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."workspace_channel_relations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."workspace_channel_relations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."workspace_channel_relations_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
